# The Docker image that will be used to build your app
image: pandoc/core
# Functions that should be executed before the build script is run
before_script: []
pages:
  script:
    - cd .binder_landing_page
    - pandoc --metadata pagetitle="VantHoffFitting" -c pandoc.css -s index.md -o
      index.html
    - cd ..
    - mkdir public
    - cp .binder_landing_page/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
