name = "VantHoffFitting"
uuid = "615b991d-b175-4143-9ab3-cee6461e2bc2"
authors = ["Jakob Tómas Bullerjahn <bullerjahn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
